export const apiUrl = 'http://localhost:8000'
export const apiUrlUser = 'http://localhost:8000/user/image'

// account
export const REQUEST_LOGIN_ACCOUNT = 'REQUEST_LOGIN_ACCOUNT'
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS'
export const LOGIN_ACCOUNT_FAIL = 'LOGIN_ACCOUNT_FAIL'


// user
export const REQUEST_REGISTER_USER = 'REQUEST_REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const REQUEST_GET_USER_TOKEN = 'REQUEST_GET_USER_TOKEN'
export const GET_USER_TOKEN_SUCCESS = 'GET_USER_TOKEN_SUCCESS'
export const GET_USER_TOKEN_FAIL = 'GET_USER_TOKEN_FAIL'

export const REQUEST_GET_USER_BY_ID = 'REQUEST_GET_USER_BY_ID'
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS'
export const GET_USER_BY_ID_FAIL = 'GET_USER_BY_ID_FAIL'

// post
export const REQUEST_ADD_POST = 'REQUEST_ADD_POST'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAIL = 'ADD_POST_FAIL'

export const REQUEST_GET_ALL_POSTS = 'REQUEST_GET_ALL_POSTS'
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS'
export const GET_ALL_POSTS_FAIL = 'GET_ALL_POSTS_FAIL'